/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rl109350
 */
import java.awt.*;
import javax.swing.*;

public class InitDlg extends javax.swing.JDialog {

    //attributs
     private int nc; // attribut permettant de connaitre le niveaux
    private LesJoueurs lj; //joueurs selectionnée
    private boolean ok;   //true  pour valider et false pour annnuler
    /**
     * Creates new form InitDlg
     */
    public InitDlg(java.awt.Frame parent, boolean modal, LesJoueurs joueurs) {
        super(parent, modal); //appel du constructeur de la classe
        initComponents();//creation de l'interface
        
        //initialisation des attributs 
        this.nc = 4;
        this.lj = joueurs;
        this.ok = false;
    }
    
//accessue en lecture
     public int getNiveau(){
        return this.nc;
    }

    public LesJoueurs getLj() {
        return this.lj;
    }

    public boolean getOK() {
        return this.ok;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tailleJeu = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Enfant = new javax.swing.JRadioButton();
        Debutant = new javax.swing.JRadioButton();
        Avance = new javax.swing.JRadioButton();
        Expert = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        CaseLara = new javax.swing.JCheckBox();
        CaseJack = new javax.swing.JCheckBox();
        CaseJean = new javax.swing.JCheckBox();
        CaseAmadeus = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        BPhoto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel1.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel1.add(Valider);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choisissez la taille du jeu");
        jPanel3.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        tailleJeu.add(Enfant);
        Enfant.setText("enfant(4 personnages, 2 familles)");
        Enfant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnfantActionPerformed(evt);
            }
        });
        jPanel4.add(Enfant);

        tailleJeu.add(Debutant);
        Debutant.setText("débutant(10 personnages, 2 familles)");
        Debutant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebutantActionPerformed(evt);
            }
        });
        jPanel4.add(Debutant);

        tailleJeu.add(Avance);
        Avance.setText("avancé (18 personnages, 4 familles)");
        Avance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvanceActionPerformed(evt);
            }
        });
        jPanel4.add(Avance);

        tailleJeu.add(Expert);
        Expert.setText("expert (32 personnages, 8 familles)");
        Expert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpertActionPerformed(evt);
            }
        });
        jPanel4.add(Expert);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Choisissez les joueurs créés par défaut");
        jPanel5.add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel6.setLayout(new java.awt.GridLayout(4, 1));

        CaseLara.setText("Lara");
        CaseLara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaseLaraActionPerformed(evt);
            }
        });
        jPanel6.add(CaseLara);

        CaseJack.setText("Jack");
        CaseJack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaseJackActionPerformed(evt);
            }
        });
        jPanel6.add(CaseJack);

        CaseJean.setText("Jean-Sébastien");
        CaseJean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaseJeanActionPerformed(evt);
            }
        });
        jPanel6.add(CaseJean);

        CaseAmadeus.setText("Amadeus");
        CaseAmadeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaseAmadeusActionPerformed(evt);
            }
        });
        jPanel6.add(CaseAmadeus);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.GridLayout(2, 1));

        Edition.setColumns(20);
        Edition.setRows(5);
        Edition.setPreferredSize(new java.awt.Dimension(100, 75));
        jScrollPane1.setViewportView(Edition);

        jPanel7.add(jScrollPane1);

        BPhoto.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel7.add(BPhoto);

        getContentPane().add(jPanel7, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
//gestionnaire du clic sur le bouton radio enfant
    
    private void EnfantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnfantActionPerformed
        // TODO add your handling code here:
        this.nc=4; 
    }//GEN-LAST:event_EnfantActionPerformed

    //gestionnaire du clic sur le bouton radio debutant
    private void DebutantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebutantActionPerformed
        // TODO add your handling code here:
        this.nc=10;
    }//GEN-LAST:event_DebutantActionPerformed

    //gestionnaire du clic sur le bouton radio avance
    private void AvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvanceActionPerformed
        // TODO add your handling code here:
        this.nc=18;
    }//GEN-LAST:event_AvanceActionPerformed

    //gestionnaire du clic sur le bouton radio expert
    private void ExpertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpertActionPerformed
        // TODO add your handling code here:
        this.nc=32;
    }//GEN-LAST:event_ExpertActionPerformed

    //gestionnaire du clic sur les cases a cocher : caseLara
    private void CaseLaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaseLaraActionPerformed
        // TODO add your handling code here:
        Joueur j=new Joueur("Lara", "épiques");
        j.setPhoto(new ImageIcon(getClass().getResource("/img/lara.jpg"))); 
        Edition.setText(j.toString());
        Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_CaseLaraActionPerformed
    //gestionnaire du clic sur les cases a cocher : caseJack

    private void CaseJackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaseJackActionPerformed
        // TODO add your handling code here:
        Joueur j=new Joueur("Jack", "rares");
        j.setPhoto(new ImageIcon(getClass().getResource("/img/jack.png"))); 
        Edition.setText(j.toString());
        Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_CaseJackActionPerformed

        //gestionnaire du clic sur les cases a cocher : caseJean
    private void CaseJeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaseJeanActionPerformed
        // TODO add your handling code here:
        Joueur j=new Joueur("Jack-Sébastien", "alpins-femmes");
        j.setPhoto(new ImageIcon(getClass().getResource("/img/bach.jpg")));
        Edition.setText(j.toString());Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_CaseJeanActionPerformed

        //gestionnaire du clic sur les cases a cocher : caseAmadeus

    private void CaseAmadeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaseAmadeusActionPerformed
        // TODO add your handling code here:
        Joueur j=new Joueur("Amadeus", "communs");
        j.setPhoto(new ImageIcon(getClass().getResource("/img/mozart.jpg"))); 
        Edition.setText(j.toString());Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_CaseAmadeusActionPerformed

        //gestionnaire du clic sur le  bouton valider qui permet de valider

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // TODO add your handling code here:
        
        if(CaseLara.isSelected()){
            Joueur j= new Joueur("Lara","épiques");
            j.setPhoto(new ImageIcon(getClass().getResource("/img/lara.jpg")));
            this.lj.ajouteJoueur(j);
        }
            
        if(CaseJack.isSelected()){
            Joueur j=new Joueur("Jack", "rares");
            j.setPhoto(new ImageIcon(getClass().getResource("/img/jack.png"))); 
            this.lj.ajouteJoueur(j);
            }
                
        if(CaseJean.isSelected()){
            Joueur j=new Joueur("Jean-Sébastien", "alpins-femmes");
            j.setPhoto(new ImageIcon(getClass().getResource("/img/bach.jpg"))); 
            this.lj.ajouteJoueur(j);
        }
        
        if(CaseAmadeus.isSelected()){
            Joueur j=new Joueur("Amadeus", "communs");
            j.setPhoto(new ImageIcon(getClass().getResource("/img/mozart.jpg"))); 
            this.lj.ajouteJoueur(j);
        }
            
        this.ok= true;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ValiderActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_AnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    
   
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InitDlg dialog = new InitDlg(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JRadioButton Avance;
    private javax.swing.JButton BPhoto;
    private javax.swing.JCheckBox CaseAmadeus;
    private javax.swing.JCheckBox CaseJack;
    private javax.swing.JCheckBox CaseJean;
    private javax.swing.JCheckBox CaseLara;
    private javax.swing.JRadioButton Debutant;
    private javax.swing.JTextArea Edition;
    private javax.swing.JRadioButton Enfant;
    private javax.swing.JRadioButton Expert;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup tailleJeu;
    // End of variables declaration//GEN-END:variables
   
}

 
