import java.awt.*;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author io366020
 */
public class JeuMemory extends javax.swing.JFrame {

    //attributs
      private LesPersonnages persos;
    private LesJoueurs joueurs;
    private Joueur j;
    
    /**
     * Creates new form JeuMemory
     */
    public JeuMemory() {
        
        initComponents();//creation de l'interface
        // initialisation des attributs et creation d'un joueur
        this.persos = new LesPersonnages();
        this.joueurs = new LesJoueurs();
        this.j = new Joueur("FanMemory", "commun");
        this.j.initPaquetTest();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Infos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        NbpersoT = new javax.swing.JLabel();
        NbpersoR = new javax.swing.JLabel();
        JC = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        Demarer = new javax.swing.JButton();
        Recommencer = new javax.swing.JButton();
        Grille = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Parametres = new javax.swing.JMenu();
        Options = new javax.swing.JMenuItem();
        AjoutJoueur = new javax.swing.JMenuItem();
        Visualiser = new javax.swing.JMenu();
        Joueur = new javax.swing.JMenuItem();
        Carte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Infos.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        NbpersoT.setText("Nb de personnages trouvés : 2");
        jPanel1.add(NbpersoT);

        NbpersoR.setText("Nb de personnages restants : 10");
        jPanel1.add(NbpersoR);

        JC.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JC.setText("C'est à Lara de Jouer !");
        jPanel1.add(JC);

        Infos.add(jPanel1, java.awt.BorderLayout.NORTH);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Infos.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        Demarer.setText("Démarer");
        jPanel2.add(Demarer);

        Recommencer.setText("Recommencer");
        jPanel2.add(Recommencer);

        Infos.add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(Infos, java.awt.BorderLayout.WEST);

        Grille.setLayout(new java.awt.GridLayout(4, 5));
        Grille.add(jButton1);
        Grille.add(jButton2);
        Grille.add(jButton3);
        Grille.add(jButton4);
        Grille.add(jButton5);
        Grille.add(jButton6);
        Grille.add(jButton7);
        Grille.add(jButton8);
        Grille.add(jButton9);
        Grille.add(jButton10);
        Grille.add(jButton11);
        Grille.add(jButton12);
        Grille.add(jButton13);
        Grille.add(jButton14);
        Grille.add(jButton15);
        Grille.add(jButton16);
        Grille.add(jButton17);
        Grille.add(jButton18);
        Grille.add(jButton19);
        Grille.add(jButton20);

        getContentPane().add(Grille, java.awt.BorderLayout.CENTER);

        Parametres.setText("Paramètres");

        Options.setText("Options");
        Options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionsActionPerformed(evt);
            }
        });
        Parametres.add(Options);

        AjoutJoueur.setText("Ajout Joueur");
        AjoutJoueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutJoueurActionPerformed(evt);
            }
        });
        Parametres.add(AjoutJoueur);

        jMenuBar1.add(Parametres);

        Visualiser.setText("Visualiser");

        Joueur.setText("Joueurs");
        Joueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoueurActionPerformed(evt);
            }
        });
        Visualiser.add(Joueur);

        Carte.setText("Cartes");
        Carte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarteActionPerformed(evt);
            }
        });
        Visualiser.add(Carte);

        jMenuBar1.add(Visualiser);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //gestionnaire de la sous option - option qui permet de visualisation la boite de dialogue InitDlg
    private void OptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionsActionPerformed
        // TODO add your handling code here:
        InitDlg init = new InitDlg(this, true, this.joueurs);
        init.setVisible(true);
    }//GEN-LAST:event_OptionsActionPerformed

        //gestionnaire de la sous option - Joueur qui permet de visualisation la boite de dialogue VisuJoueursDlg

    private void JoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JoueurActionPerformed
        // TODO add your handling code here:
        VisuJoueursDlg visu = new VisuJoueursDlg(this, true, this.joueurs);
        visu.setVisible(true);
    }//GEN-LAST:event_JoueurActionPerformed

    
   //gestionnaire de la sous option - AjoutJoueur qui permet de visualisation la boite de dialogue SaisieJoueurDlg
    private void AjoutJoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutJoueurActionPerformed
        // TODO add your handling code here:
        SaisieJoueurDlg saisie = new SaisieJoueurDlg(this, true, this.joueurs);
        saisie.setVisible(true);
    }//GEN-LAST:event_AjoutJoueurActionPerformed

    //gestionnaire de la sous option - Carte permettant de visualiser la boite de dialogue VisuPersonnagesDlg (les personnages)
    private void CarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarteActionPerformed
        // TODO add your handling code here:
        VisuPersonnagesDlg visu = new VisuPersonnagesDlg(this, true, this.j);
        visu.setVisible(true);
    }//GEN-LAST:event_CarteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JeuMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JeuMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JeuMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JeuMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JeuMemory  lc=new JeuMemory();
                lc.setSize(600,600);
                lc.setTitle("Jeu Memory");
                lc.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AjoutJoueur;
    private javax.swing.JMenuItem Carte;
    private javax.swing.JButton Demarer;
    private javax.swing.JPanel Grille;
    private javax.swing.JPanel Infos;
    private javax.swing.JLabel JC;
    private javax.swing.JMenuItem Joueur;
    private javax.swing.JLabel NbpersoR;
    private javax.swing.JLabel NbpersoT;
    private javax.swing.JMenuItem Options;
    private javax.swing.JMenu Parametres;
    private javax.swing.JButton Recommencer;
    private javax.swing.JMenu Visualiser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
  
}
