/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author io366020
 */
import javax.swing.*;
import java.io.*;
import java.awt.*;

public class SaisieJoueurDlg extends javax.swing.JDialog {
    
    //attributs
    private Joueur joueur;
    private boolean ok;
    private ImageIcon photo;
    private LesJoueurs lj;
    private LesPersonnages lp;

    /**
     * Creates new form SaisieJoueurDlg
     */
    
    //constructeur avec parametre et initialisation des attributs
    public SaisieJoueurDlg(java.awt.Frame parent, boolean modal, LesJoueurs lj) {
        super(parent, modal);//appel du constructeur de la classe ancentre
        initComponents();//creation de l'interface
        this.lj = lj;
        this.lp= new LesPersonnages();
        
        this.joueur = new Joueur();
        
        DefaultListModel mod = new DefaultListModel();
        ListeFamilles.setModel(mod);
        initListeFamilles();
    }
    
    //accesseurs en lecture
    public Joueur getJoueur(){
        return this.joueur;
    }
    
    public boolean getOk(){
        return this.ok;
    }
    
    //méthodes
    private void initListeFamilles(){
        DefaultListModel mod = (DefaultListModel)ListeFamilles.getModel();
        mod.addElement("communs");
        mod.addElement("rares");
        mod.addElement("épiques");
        mod.addElement("alpins-femmes");
        mod.addElement("as-des-pistes");
        mod.addElement("légendaires");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Pseudo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeFamilles = new javax.swing.JList<String>();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Parcourir = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        Photo = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Créez votre joueur !");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setLayout(new java.awt.GridLayout(3, 1));

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Donnez votre pseudo :");
        jPanel4.add(jLabel2, java.awt.BorderLayout.NORTH);
        jPanel4.add(Pseudo, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Quelle est votre famille préférée de personnages :");
        jPanel5.add(jLabel3, java.awt.BorderLayout.NORTH);

        ListeFamilles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(ListeFamilles);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Choisissez une photo :");
        jPanel6.add(jLabel4, java.awt.BorderLayout.NORTH);

        Parcourir.setText("Parcourir");
        Parcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParcourirActionPerformed(evt);
            }
        });
        jPanel6.add(Parcourir, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6);

        jPanel2.add(jPanel3);

        jPanel7.setLayout(new java.awt.BorderLayout());
        jPanel7.add(Photo, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel8.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel8.add(Valider);

        jPanel7.add(jPanel8, java.awt.BorderLayout.SOUTH);

        jPanel2.add(jPanel7);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //gestionnaire de parcourir qui permet de chosiir l'image du joueur
    private void ParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParcourirActionPerformed
        // TODO add your handling code here:
        JFileChooser jf= new JFileChooser();
        if (jf.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)
        {
            String path = jf.getSelectedFile().getPath();
            Image img=Toolkit.getDefaultToolkit().getImage(path);
            img=img.getScaledInstance(Photo.getWidth()-10, Photo.getHeight()-10, Image.SCALE_DEFAULT);
            this.photo = new ImageIcon(img);
            Photo.setIcon(this.photo);
        }
    }//GEN-LAST:event_ParcourirActionPerformed

    //gestionnaire de valider quin permet de valider la saisie du joueur
    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // TODO add your handling code here:
        
        // Si un élément de la JList est sélectionné et que le champ de texte n'est pas vide 
        // On crée une nouvelle instance de Joueur contenant le pseudo du champ de texte et l'élément de la Jlist en paramètres
        if(ListeFamilles.getSelectedIndex() != -1 && !Pseudo.getText().equals("")){
            this.joueur = new Joueur(Pseudo.getText(), ListeFamilles.getSelectedValue());
            this.ok = true;
        }
        else
            Pseudo.setText("Erreur dans la création du joueur !");
        
        if(this.getOk()){
            if(Photo.getIcon()!= null)
                this.joueur.setPhoto(this.photo);
            
            this.lj.ajouteJoueur(this.getJoueur());
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_ValiderActionPerformed

    //gestionnaire permettant d'annuler le boite de dialogue et annuler tous les informations saisie
    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // TODO add your handling code here:
        this.ok = false; //car pas valider
        this.setVisible(false);//ferme la fenetre
        this.dispose(); //pour mieux liberer l'espace memoire   
    }//GEN-LAST:event_AnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaisieJoueurDlg dialog = new SaisieJoueurDlg(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JList<String> ListeFamilles;
    private javax.swing.JButton Parcourir;
    private javax.swing.JButton Photo;
    private javax.swing.JTextField Pseudo;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
 
}
