/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author io366020
 */
import javax.swing.*;
import java.awt.*;

public class VisuPersonnagesDlg extends javax.swing.JDialog {

    private Joueur joueur; //attribut jour de type joueur
    
    /**
     * Creates new form VisuPersonnagesDlg
     */
    public VisuPersonnagesDlg(java.awt.Frame parent, boolean modal, Joueur joueur) {
        super(parent, modal);
        initComponents();
        this.joueur =  joueur;
        initPanneau(); //methode du panneau qui contient les trombinoscope
        Perso.setText("Cartes du joueur : " + this.joueur.getNom());
        Score.setText("Score : " + this.joueur.getPaquet().getScore());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Perso = new javax.swing.JLabel();
        Panneau = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Score = new javax.swing.JLabel();
        Afficher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));

        Perso.setText("Cartes du joueur :");
        getContentPane().add(Perso, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout PanneauLayout = new javax.swing.GroupLayout(Panneau);
        Panneau.setLayout(PanneauLayout);
        PanneauLayout.setHorizontalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        PanneauLayout.setVerticalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(Panneau, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        Score.setText("Score :");
        jPanel1.add(Score);

        Afficher.setText("Afficher");
        Afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherActionPerformed(evt);
            }
        });
        jPanel1.add(Afficher);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //gestionnaire d'afficher qui permet d'afficher les cartes des personnages gagnés par le joueur 
    private void AfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherActionPerformed
        // TODO add your handling code here:
        JButton jb;
        for(int i = 0; i < this.joueur.getPaquet().getTaille(); i++){
            jb = (JButton)Panneau.getComponent(i);
            Image img = this.joueur.getPaquet().getPerso(i).getPhoto().getScaledInstance(jb.getWidth(), jb.getHeight(), Image.SCALE_SMOOTH);
            jb.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_AfficherActionPerformed

    //methode Panneau
    private void initPanneau(){
        int nb = this.joueur.getPaquet().getTaille();
        Panneau.setLayout(new GridLayout(1, nb));
        for (int i=0; i< nb; i++){
            JButton jb = new JButton();
            Personnage p = this.joueur.getPaquet().getPerso(i);
            jb.setName("" + i);
            Panneau.add(jb);
        }
        this.pack(); // pour ajuster correctement la taille des composants après les ajouts si besoin
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuPersonnagesDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuPersonnagesDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuPersonnagesDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuPersonnagesDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisuPersonnagesDlg dialog = new VisuPersonnagesDlg(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Afficher;
    private javax.swing.JPanel Panneau;
    private javax.swing.JLabel Perso;
    private javax.swing.JLabel Score;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
